// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QueryMind.Api.Data;

#nullable disable

namespace QueryMind.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261010172025_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QueryMind.Api.Data.QueryAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("AttemptNo")
                        .HasColumnType("smallint")
                        .HasColumnName("attempt_no");

                    b.Property<int?>("CompletionTokens")
                        .HasColumnType("integer")
                        .HasColumnName("completion_tokens");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("text")
                        .HasColumnName("error_code");

                    b.Property<Guid>("HistoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("history_id");

                    b.Property<int>("LatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("latency_ms");

                    b.Property<int?>("PromptTokens")
                        .HasColumnType("integer")
                        .HasColumnName("prompt_tokens");

                    b.Property<string>("Sql")
                        .HasColumnType("text")
                        .HasColumnName("sql");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stage");

                    b.HasKey("Id")
                        .HasName("pk_query_attempts");

                    b.HasIndex("HistoryId", "AttemptNo")
                        .IsUnique()
                        .HasDatabaseName("ix_query_attempts_history_id_attempt_no");

                    b.ToTable("query_attempts", null, t =>
                        {
                            t.HasCheckConstraint("ck_query_attempts_attempt_no", "attempt_no >= 1");

                            t.HasCheckConstraint("ck_query_attempts_stage", "stage IN ('extract', 'validate', 'execute')");
                        });
                });

            modelBuilder.Entity("QueryMind.Api.Data.QueryHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChartType")
                        .HasColumnType("text")
                        .HasColumnName("chart_type");

                    b.Property<int?>("CompletionTokens")
                        .HasColumnType("integer")
                        .HasColumnName("completion_tokens");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("EngineTotalMs")
                        .HasColumnType("integer")
                        .HasColumnName("engine_total_ms");

                    b.Property<int?>("ExecutionMs")
                        .HasColumnType("integer")
                        .HasColumnName("execution_ms");

                    b.Property<string>("FinalSql")
                        .HasColumnType("text")
                        .HasColumnName("final_sql");

                    b.Property<int?>("GenerationMs")
                        .HasColumnType("integer")
                        .HasColumnName("generation_ms");

                    b.Property<int?>("LinkingMs")
                        .HasColumnType("integer")
                        .HasColumnName("linking_ms");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Model")
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<int?>("PromptTokens")
                        .HasColumnType("integer")
                        .HasColumnName("prompt_tokens");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question");

                    b.Property<Guid?>("RerunOfId")
                        .HasColumnType("uuid")
                        .HasColumnName("rerun_of_id");

                    b.Property<int?>("RowCount")
                        .HasColumnType("integer")
                        .HasColumnName("row_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int?>("SummaryMs")
                        .HasColumnType("integer")
                        .HasColumnName("summary_ms");

                    b.Property<int?>("TotalMs")
                        .HasColumnType("integer")
                        .HasColumnName("total_ms");

                    b.Property<bool?>("Truncated")
                        .HasColumnType("boolean")
                        .HasColumnName("truncated");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int?>("ValidationMs")
                        .HasColumnType("integer")
                        .HasColumnName("validation_ms");

                    b.HasKey("Id")
                        .HasName("pk_query_history");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_query_history_created_at");

                    b.HasIndex("RerunOfId")
                        .HasDatabaseName("ix_query_history_rerun_of_id");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_query_history_user_id_created_at");

                    b.ToTable("query_history", null, t =>
                        {
                            t.HasCheckConstraint("ck_query_history_status", "status IN ('success', 'failed', 'blocked', 'cannot_answer', 'error')");
                        });
                });

            modelBuilder.Entity("QueryMind.Api.Data.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("user")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_role", "role IN ('user', 'admin')");
                        });
                });

            modelBuilder.Entity("QueryMind.Api.Data.QueryAttempt", b =>
                {
                    b.HasOne("QueryMind.Api.Data.QueryHistory", "History")
                        .WithMany("Attempts")
                        .HasForeignKey("HistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_query_attempts_query_history_history_id");

                    b.Navigation("History");
                });

            modelBuilder.Entity("QueryMind.Api.Data.QueryHistory", b =>
                {
                    b.HasOne("QueryMind.Api.Data.QueryHistory", "RerunOf")
                        .WithMany()
                        .HasForeignKey("RerunOfId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_query_history_query_history_rerun_of_id");

                    b.HasOne("QueryMind.Api.Data.User", "User")
                        .WithMany("History")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_query_history_users_user_id");

                    b.Navigation("RerunOf");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QueryMind.Api.Data.QueryHistory", b =>
                {
                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("QueryMind.Api.Data.User", b =>
                {
                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
